apiversion: v2
name: onecx-welcome
version: 0.0.0
appversion: 0.0.0
dependencies:
- name: helm-product
  version: ^0
  repository: oci://ghcr.io/onecx/charts
  alias: product
- name: onecx-welcome-svc
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.svc"
  alias: "svc"
- name: onecx-welcome-bff
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.bff"
  alias: "bff"
- name: onecx-welcome-ui
  version: "*-0"
  repository: oci://ghcr.io/onecx/charts
  condition: "deployment.ui"
  alias: "ui"
