deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX Welcome"
      imageUrl: ""
      iconName: "home"
      displayName: "OneCX Welcome"
      basePath: "/welcome"
